# Generated by Django 6.0.1 on 2026-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='requires_acknowledgment',
            field=models.BooleanField(default=False),
        ),
    ]
