# Generated by Django 6.0.1 on 2026-03-12 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_requires_acknowledgment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.IntegerField(choices=[(1, 'Message 1'), (2, 'Message 2'), (3, 'Message 3'), (4, 'Message 4')], unique=True)),
                ('message', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reminder_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
