# Generated by Django 6.0.1 on 2026-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ensure_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
