# Generated by Django 6.0.1 on 2026-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditincreaserequest',
            name='requested_term',
            field=models.IntegerField(blank=True, help_text='Requested credit term in days', null=True),
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='requested_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
