# Generated by Django 6.0.1 on 2026-04-06 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_must_change_flag(apps, schema_editor):
    Customer = apps.get_model('accounts', 'Customer')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for customer in Customer.objects.filter(must_change_password=True):
        UserProfile.objects.get_or_create(
            user=customer.user,
            defaults={'must_change_password': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_creditincreaserequest_requested_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(migrate_must_change_flag, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customer',
            name='must_change_password',
        ),
    ]
