# Generated by Django 6.0.1 on 2026-02-01 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_mode', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='DELIVERY', max_length=50)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.creditaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.branch')),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_approved', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompletion',
            fields=[
                ('completion_id', models.AutoField(primary_key=True, serialize=False)),
                ('completion_status', models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup/Delivery'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('override_id', models.AutoField(primary_key=True, serialize=False)),
                ('override_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('override_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('approving_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='override_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='orders.order')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='override_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
