# Generated by Django 6.0.1 on 2026-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_name_alter_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
