from django.urls import path
from .views import (
    create_order, 
    customer_orders, 
    order_detail,
    cm_all_orders,
    cm_pending_orders,
    cm_order_detail,
    cm_approve_order,
    cm_reject_order,
    cm_request_override,
    um_pending_overrides,
    um_pending_orders,
    um_override_detail,
    um_approve_override,
    um_reject_override,
    cm_customers_list,
    cm_customer_history,
    cm_adjust_customer_balance,
    op_pending_orders,
    op_order_detail,
    op_complete_order,
    op_completed_orders,
    op_order_view,
    um_customers_list,
    um_customer_detail,
    um_update_customer_balance,
    um_delete_customer,
    um_customer_orders,
    um_all_orders,
)

urlpatterns = [
    path('api/orders/create/', create_order),
    path('api/orders/', customer_orders),
    path('api/orders/<int:order_id>/', order_detail),
    
    # Credit Manager endpoints
    path('api/cm/all-orders/', cm_all_orders),
    path('api/cm/pending-orders/', cm_pending_orders),
    path('api/cm/order/<int:order_id>/', cm_order_detail),
    path('api/cm/order/<int:order_id>/approve/', cm_approve_order),
    path('api/cm/order/<int:order_id>/reject/', cm_reject_order),
    path('api/cm/order/<int:order_id>/request-override/', cm_request_override),
    path('api/cm/customers/', cm_customers_list),
    path('api/cm/customer/<int:customer_id>/history/', cm_customer_history),
    path('api/cm/customer/<int:customer_id>/adjust-balance/', cm_adjust_customer_balance),
    
    # Upper Management endpoints
    path('api/um/pending-overrides/', um_pending_overrides),
    path('api/um/pending-orders/', um_pending_orders),
    path('api/um/override/<int:override_id>/', um_override_detail),
    path('api/um/override/<int:override_id>/approve/', um_approve_override),
    path('api/um/override/<int:override_id>/reject/', um_reject_override),
    path('api/um/customers/', um_customers_list),
    path('api/um/customer/<int:customer_id>/', um_customer_detail),
    path('api/um/customer/<int:customer_id>/update-balance/', um_update_customer_balance),
    path('api/um/customer/<int:customer_id>/delete/', um_delete_customer),
    path('api/um/customer/<int:customer_id>/orders/', um_customer_orders),
    path('api/um/all-orders/', um_all_orders),
    
    # Order Processor endpoints
    path('api/op/pending-orders/', op_pending_orders),
    path('api/op/order/<int:order_id>/', op_order_detail),
    path('api/op/order/<int:order_id>/complete/', op_complete_order),
    path('api/op/completed-orders/', op_completed_orders),
    path('api/op/order/<int:order_id>/view/', op_order_view),
]