# Generated by Django 6.0.1 on 2026-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_activation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditenrollment',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
