# Generated by Django 6.0.1 on 2026-02-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('applications', '0004_creditenrollment_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditenrollment',
            name='default_branch',
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch'),
        ),
    ]
