# Generated by Django 6.0.1 on 2026-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_creditenrollment_default_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditenrollment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
