# Generated by Django 6.0.1 on 2026-03-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_creditenrollment_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_address1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_address2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditenrollment',
            name='billing_zipcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
