# Generated by Django 6.0.1 on 2026-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_creditenrollment_billing_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditenrollment',
            name='doc3_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/'),
        ),
    ]
