# Generated by Django 6.0.1 on 2026-04-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_creditenrollment_doc3_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditenrollment',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='doc1_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/'),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='doc2_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/'),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='gov_id',
            field=models.FileField(blank=True, null=True, upload_to='applications/gov_ids/'),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditenrollment',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
