# Generated by Django 6.0.1 on 2026-02-01 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_number', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField()),
                ('proof_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounts.creditaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
