# Generated by Django 6.0.1 on 2026-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
