# Generated by Django 6.0.1 on 2026-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('GCASH', 'GCash'), ('CHECK', 'Check')], default='', max_length=30),
        ),
    ]
