# Generated by Django 6.0.1 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrequest_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('BANK_DEPOSIT', 'Bank Deposit'), ('PALAWAN', 'Palawan Remittance'), ('BRANCH_CASH', 'Branch Cash Payment'), ('BRANCH_CHECK', 'Branch Check Payment')], default='', max_length=30),
        ),
    ]
